apiVersion: v1
kind: Secret
metadata:
  name: order-subscriber-secret
  namespace: demo
type: Opaque
data:
  DB_HOST: MTAuMjEzLjAuMg==
  DB_PORT: NjQzMg==
  DB_USER: cG9zdGdyZXM=
  DB_PASSWORD: cnVVQV8tYk1CI0JhOlBQRw== 
  DB_NAME: cG9zdGdyZXM=