apiVersion: v1
kind: ServiceAccount
metadata:
  name: gcp-pubsub-subscriber-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: your-gsa@your-gcp-project-id.iam.gserviceaccount.com
